# Generated by Django 4.2.13 on 2024-12-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('start_date', models.CharField(default='01-01-2000', max_length=20)),
                ('end_date', models.CharField(default='01-01-2000', max_length=20)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('position', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('contact_number', models.CharField(default='N/A', max_length=15)),
                ('hiring_date', models.CharField(default='01-01-2000', max_length=30)),
            ],
        ),
    ]
