# Generated by Django 4.2.13 on 2024-12-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='name',
        ),
    ]
