# Generated by Django 4.2.20 on 2025-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_locationdetail_delete_locationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetail',
            name='latitude_clock_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locationdetail',
            name='longitude_clock_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locationdetail',
            name='timestamp_clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
